name: CI - AI Engineer Projects

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  model-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run notebook smoke tests
        run: |
          pip install nbmake
          pytest --nbmake notebooks/
